FROM rust:1.45.2-stretch as builder

RUN USER=root cargo new --lib ctl2mimir
WORKDIR ./ctl2mimir
COPY ./Cargo.toml ./Cargo.toml

RUN apt-get update \
    && apt-get install -y sqlite3 \
    && apt-get install -y libzmq5-dev
RUN cargo build --lib --release
RUN rm src/*.rs

ADD . ./

RUN rm ./target/release/deps/ctl2mimir*
RUN cargo build --release

FROM rust:1.45.2-stretch
ARG APP=/usr/src/app

RUN apt-get update \
    && apt-get install -y libzmq5-dev \
    && apt-get install -y libgeos-c1v5 libgeos-dev\
    && apt-get install -y netcat \
    && apt-get install -y ca-certificates tzdata \
    && rm -rf /var/lib/apt/lists/*

ENV TZ=Etc/UTC \
    RUN_MODE=development \
    APP_USER=appuser

RUN groupadd $APP_USER \
    && useradd -g $APP_USER $APP_USER \
    && mkdir -p ${APP}

ENV SQLITE_FILE=${SQLITE_FILE}
RUN cargo install movine

COPY --from=builder /ctl2mimir/target/release/service ${APP}/service
COPY --from=builder /ctl2mimir/config ${APP}/config
COPY --from=builder /ctl2mimir/migrations ${APP}/migrations
COPY --from=builder /ctl2mimir/${SQLITE_FILE} ${APP}/${SQLITE_FILE}
COPY --from=builder /ctl2mimir/docker/entrypoint.sh ${APP}/entrypoint.sh

RUN chown -R $APP_USER:$APP_USER ${APP}

USER $APP_USER
WORKDIR ${APP}

CMD ["./entrypoint.sh"]
