debug = true
mode = "development"

[database]
url = "hello.db"

[zmq]
host = "127.0.0.1"
port = "5555"

[elasticsearch]
host = "elasticsearch"
port = "9200"

[work]
working_dir = "/usr/src/app/work"
mimirsbrunn_dir = "/srv/mimir"
cosmogony_dir = "/srv/cosmogony"

[service]
host = "0.0.0.0"
port = "5000"
