debug = true
mode = "development"

[database]
url = "sqlite://hello.db"

[zmq]
host = "127.0.0.1"
port = "5555"
topic = "state"

[elasticsearch]
host = "elasticsearch"
port = "9200"

[work]
working_dir = "/var/opt/mimir_ingest/work"
mimirsbrunn_dir = "/opt/mimirsbrunn"
cosmogony_dir = "/opt/cosmogony"

[service]
host = "0.0.0.0"
port = "5000"
